# Generated by Django 2.2.2 on 2019-08-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_remove_vote_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
