# Generated by Django 2.2.2 on 2019-08-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20190821_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.TextField(),
        ),
    ]

