# Generated by Django 2.2.2 on 2019-08-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_auto_20190821_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='question_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
