# Generated by Django 2.2.4 on 2019-09-04 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0015_auto_20190902_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Course location')),
            ],
        ),
        migrations.AlterField(
            model_name='vote',
            name='question_id',
            field=models.ForeignKey(on_delete=models.SET(0), to='vote.Question'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Course code')),
                ('title', models.CharField(max_length=255, verbose_name='Course title')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Course start date')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vote.Location')),
            ],
        ),
    ]
