# Generated by Django 2.2.4 on 2019-09-07 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0019_auto_20190904_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='comment_data',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
