# Generated by Django 2.2.4 on 2019-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0021_auto_20190919_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
