# Generated by Django 2.2.4 on 2019-10-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='plain_text_template',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='subject_line_template',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='from_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='plain_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='template_key',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='to_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
