# Generated by Django 2.2.4 on 2019-09-24 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btbadmin', '0004_auto_20190920_0057'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ptpadmin', '0003_centrecourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btbadmin.Centre')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
