# Generated by Django 2.2.6 on 2019-11-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataCapture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('gdpr_opt_in', models.BooleanField(default=False, verbose_name='GDPR Opt-in')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
