# Generated by Django 2.2.4 on 2019-09-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btbadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='admin_user_group',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Group'),
        ),
    ]
