# Generated by Django 2.2.4 on 2019-09-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btbadmin', '0002_centre_admin_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='admin_user_group',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Group'),
        ),
    ]
