# Generated by Django 2.2.4 on 2019-09-20 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btbadmin', '0003_auto_20190919_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='admin_user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
