# Generated by Django 2.2.4 on 2019-09-30 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btbadmin', '0004_auto_20190920_0057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
