# Generated by Django 2.2.6 on 2019-10-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='stage',
            new_name='status',
        ),
    ]
