# Generated by Django 2.2.4 on 2019-09-23 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btbadmin', '0004_auto_20190920_0057'),
        ('domain_admin', '0002_auto_20190923_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btbadmin.Centre')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_admin.Course')),
            ],
        ),
    ]
