# Generated by Django 2.2.4 on 2019-09-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_admin', '0004_usercentre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CentreCourse',
        ),
    ]
